### ISSUE TITLE
Tracking Issue: Arm Compilation Support

### ISSUE THREAD

**Issue by chorman0773** [lccc-project/lccc#11]
Tracking issue for supporting arm (including aarch64):

Tasks:
- [ ] Add xlang_target properties for arm/aarch64 and a full target for arm/aarch64
- [ ] Add `xlangcodegen-arm`
- [ ] Run rust tests on arm
