### ISSUE TITLE
Tracking Issue: Holeybytes Compilation support

### ISSUE THREAD

**Issue by chorman0773** [lccc-project/lccc#9]
Add support for the HoleyBytes Virtual Machine ISA.

**Comment by chorman0773** [comment]
Tasks:
- [x] Add xlang_target properties for holeybytes and a full target for holeybytes
- [ ] Add `xlangcodegen-holeybytes`
- [ ] Run rust tests on holeybytes
